# Generated by Django 5.1.2 on 2024-11-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admins', 'Admins'), ('Librarians', 'Librarians'), ('Member', 'Member')], max_length=20),
        ),
    ]
